"""add hec_ras_scenarios table

Revision ID: 3e1678526bf7
Revises: a1b2c3d4e5f6
Create Date: 2025-12-24 10:51:00.165605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1678526bf7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hec_ras_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extent_west', sa.Float(), nullable=False),
    sa.Column('extent_south', sa.Float(), nullable=False),
    sa.Column('extent_east', sa.Float(), nullable=False),
    sa.Column('extent_north', sa.Float(), nullable=False),
    sa.Column('camera_height', sa.Float(), nullable=False),
    sa.Column('camera_heading', sa.Float(), nullable=False),
    sa.Column('camera_pitch', sa.Float(), nullable=False),
    sa.Column('frames_path', sa.String(length=512), nullable=False),
    sa.Column('stats_path', sa.String(length=512), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('frame_extension', sa.String(length=10), nullable=False),
    sa.Column('legend_title', sa.String(length=100), nullable=True),
    sa.Column('legend_min', sa.Float(), nullable=True),
    sa.Column('legend_max', sa.Float(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hec_ras_scenarios_code'), 'hec_ras_scenarios', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hec_ras_scenarios_code'), table_name='hec_ras_scenarios')
    op.drop_table('hec_ras_scenarios')
    # ### end Alembic commands ###
