"""add_hydrological_stations

Revision ID: f91e0d8d3d28
Revises: fbe21847efec
Create Date: 2025-12-02 13:03:08.670851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f91e0d8d3d28'
down_revision: Union[str, Sequence[str], None] = 'fbe21847efec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydrological_stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('station_code', sa.String(length=50), nullable=False),
    sa.Column('station_name', sa.String(length=200), nullable=False),
    sa.Column('river_name', sa.String(length=200), nullable=True),
    sa.Column('basin_name', sa.String(length=200), nullable=True),
    sa.Column('cross_section', geoalchemy2.types.Geometry(geometry_type='LINESTRINGZ', srid=4549, from_text='ST_GeomFromEWKT', name='geometry', nullable=True), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=True), nullable=True),
    sa.Column('datum_elevation', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['monitoring_facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_code')
    )
    # GeoAlchemy2 creates spatial indexes automatically, no need for explicit index creation
    op.add_column('sensors', sa.Column('hydrological_station_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sensors', 'hydrological_stations', ['hydrological_station_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensors', type_='foreignkey')
    op.drop_column('sensors', 'hydrological_station_id')
    op.drop_table('hydrological_stations')
    # ### end Alembic commands ###
