"""add_orange_tree_postgis_model

Revision ID: 1f2badb4efd8
Revises: 3e1678526bf7
Create Date: 2026-06-03 21:54:37.430340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1f2badb4efd8'
down_revision: Union[str, Sequence[str], None] = '3e1678526bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orange_trees',
    sa.Column('id', sa.Integer(), nullable=False, comment='树木唯一身份证号'),
    sa.Column('batch_id', sa.String(), nullable=False, comment='数据批次标签(如历史示范区或上传时间戳)'),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=32650), nullable=False, comment='树木中心点空间要素(UTM 50N 平面直角坐标)'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='SAM 模型边缘分割置信度'),
    sa.Column('compactness', sa.Float(), nullable=True, comment='树冠圆度/紧凑度'),
    sa.Column('shape_length', sa.Float(), nullable=True, comment='树冠几何边界周长(米)'),
    sa.Column('shape_area', sa.Float(), nullable=True, comment='树冠几何边界面真面积(平方米)'),
    sa.Column('value', sa.Float(), nullable=True, comment='原始栅格像素值'),
    sa.Column('count', sa.Float(), nullable=True, comment='树冠包含的像素计数'),
    sa.Column('area_m2', sa.Float(), nullable=True, comment='栅格反演树冠投影面积(平方米)'),
    sa.Column('height_m', sa.Float(), nullable=True, comment='Meta 大模型反演物理树高(米)'),
    sa.Column('crown_diameter', sa.Float(), nullable=True, comment='树冠冠幅直径(米)'),
    sa.Column('volume_m3', sa.Float(), nullable=True, comment='脐橙树三维材积估计(立方米)'),
    sa.Column('growth_index', sa.Float(), nullable=True, comment='生长势头/健康综合指数'),
    sa.Column('slope_degree', sa.Float(), nullable=True, comment='所在山头地形坡度(度)'),
    sa.Column('aspect', sa.Float(), nullable=True, comment='所在山头地形坡向(度)'),
    sa.Column('fertilizer_level', sa.Integer(), nullable=False, comment='变量施肥建议等级(0:未计算, 1:轻度, 2:中度, 3:重度)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orange_trees_batch_id'), 'orange_trees', ['batch_id'], unique=False)
    op.create_index(op.f('ix_orange_trees_id'), 'orange_trees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orange_trees_id'), table_name='orange_trees')
    op.drop_index(op.f('ix_orange_trees_batch_id'), table_name='orange_trees')
    op.drop_table('orange_trees')
    # ### end Alembic commands ###
