"""add_flood_scenarios

Revision ID: 3d5b20b9361d
Revises: f91e0d8d3d28
Create Date: 2025-12-08 18:04:29.260969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3d5b20b9361d'
down_revision: Union[str, Sequence[str], None] = 'f91e0d8d3d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flood_scenarios',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('code', sa.String(length=50), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('region_center', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326,
                                                                          dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
                    sa.Column('region_extent', sa.Float(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_index('idx_flood_scenarios_region_center', 'flood_scenarios', [
                    'region_center'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('flood_frames',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('scenario_id', sa.Integer(), nullable=False),
                    sa.Column('time_step', sa.Integer(), nullable=False),
                    sa.Column('water_level', sa.Float(), nullable=False),
                    sa.Column('area_km2', sa.Float(), nullable=False),
                    sa.Column('polygons', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326,
                                                                     dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['scenario_id'], ['flood_scenarios.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_flood_frames_polygons', 'flood_frames', [
                    'polygons'], unique=False, postgresql_using='gist', if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_flood_frames_polygons',
                  table_name='flood_frames', postgresql_using='gist')
    op.drop_table('flood_frames')
    op.drop_index('idx_flood_scenarios_region_center',
                  table_name='flood_scenarios', postgresql_using='gist')
    op.drop_table('flood_scenarios')
    # ### end Alembic commands ###
